
#### SQL CREATE
# CREATE TABLE PUPIL
# 			(STUDENT_ID int,
# 			 STUDENT_NAME text,
# 			 STUDENT_SURNAME text,
# 			 STUDENT_COURSE int,
# 			 STUDENT_COURSE_NAME text,
# 			 STUDENT_AVE_MARK decimal,
# 			 STUDENT_TOTAL_TASK_SLOVED int
# 			 )